export interface TeamMember {
    name: string;
    title: string;
    bio?: string;
    url?: string;
    avatar: string;
    expertise?: string[];
    institution?: string;
}

export const ACTIVE_MEMBERS: TeamMember[] = [
    {
        name: 'Franco Pestilli',
        title: 'Founder and Director',
        institution: 'University of Texas at Austin',
        bio: "Franco is Associate Professor of Psychology at the University of Texas, Austin. Franco holds a Ph.D. from New York University and a Laurea Summa Cum Laude from the University of Rome La Sapienza. Franco trained as a Postdoctoral Researcher at Columbia University, Stanford University, and RIKEN Brain Science Institute. Franco's research spans across psychology, computer science, and neuroscience. He is a Fellow of the Association for Psychological Science and Psychonomics Society and has received a Microsoft Investigator Fellowship and Janet Taylor Spence Award. Franco leads brainlife.io and the BRAIN Initiative efforts to describe brain connectivity and network data.",
        url: 'https://liberalarts.utexas.edu/psychology/faculty/fp4834',
        avatar: '/img/team/franco.jpg',
        expertise: ['Neuroscience', 'BIDS Standards', 'Connectomics', 'Open Science'],
    },
    {
        name: 'Kimberly Ray',
        title: 'Research Assistant Professor',
        institution: 'University of Texas at Austin',
        bio: 'Kimberly is a Research Assistant Professor focusing on Data Standards and Sharing, Neuroimaging, and Meta-analysis. Kim holds a PhD in Human NeuroImaging from the University of Texas Health Science Center in San Antonio. She is interested in using neuroimaging to understand the functional organization of human brain networks in healthy and diseased populations.',
        url: 'https://scholar.google.com/citations?user=Qt6OuAkAAAAJ&hl=en',
        avatar: '/img/team/KimRay.jpg',
        expertise: ['Data Standards and Sharing', 'Neuroimaging', 'Meta-analysis', 'Functional Networks'],
    },
    {
        name: 'Gabriele Amorosino',
        title: 'Postdoctoral Researcher',
        institution: 'University of Texas at Austin',
        bio: 'Gabriele Amorosino holds a PhD in Cognitive and Brain Sciences from the University of Trento. He investigates how the structural organization of the brain constrains visual perception and behavior. Using brainlife.io, he develops NeuroAI models and neuroimaging pipelines.',
        url: 'https://scholar.google.com/citations?user=oRFlrk0AAAAJ&hl=en&oi=ao',
        avatar: '/img/team/gabriele.jpg',
        expertise: ['NeuroAI', 'Neuroimaging Pipelines', 'Visual Perception', 'Structural Connectivity'],
    },
    {
        name: 'Marietjie Botes',
        title: 'Postdoctoral Scholar',
        institution: 'University of Texas at Austin',
        bio: 'Marietjie is a legal expert in open science data governance, health law, research ethics, bioethics, and compliance frameworks.',
        avatar: '/img/team/Marietje.png',
        expertise: ['Legal Expert', 'Data Governance', 'Health Law & Bioethics', 'FAIR Compliance'],
    },
    {
        name: 'Blaire Porter',
        title: 'NSF SBE Postdoctoral Fellow',
        institution: 'University of Texas at Austin',
        bio: 'Blaire is an NSF SBE Postdoctoral Fellow researching Global Equity, Developmental Cognitive Neuroscience, and equitable access to neuroimaging computing.',
        avatar: '/img/team/Blair.png',
        expertise: ['Global Equity', 'Developmental Cognitive Neuroscience', 'Neurodevelopment'],
    },
    {
        name: 'Anibal S. Heinsfeld',
        title: 'Computer Science PhD Student',
        institution: 'University of Texas at Austin',
        bio: 'Anibal is a graduate research assistant in Computer Science working on software engineering, machine learning, and agentic AI applied to neuroscience data. Anibal has contributed to several open-source projects such as C-PAC, OpenNeuro, and BrainBox.',
        url: 'https://scholar.google.com/citations?user=gQdfws4AAAAJ&hl=en&oi=ao',
        avatar: '/img/team/anibalsolon.jpg',
        expertise: ['Computer Science', 'Software Engineering', 'Agentic AI', 'Machine Learning'],
    },
    {
        name: 'Junbeom Kwon',
        title: 'Psychology PhD Student',
        institution: 'University of Texas at Austin',
        bio: 'Junbeom is a Psychology PhD student developing NeuroAI models, diffusion MRI tools, and automated neuroimaging analysis pipelines on brainlife.io.',
        avatar: '/img/team/junbeom_kwon.jpg',
        expertise: ['Psychology', 'Neuroimaging', 'NeuroAI', 'Diffusion MRI'],
    },
    {
        name: 'Stephen Kiilu',
        title: 'Psychology PhD Student',
        institution: 'University of Texas at Austin',
        bio: 'Stephen is a Psychology PhD student researching aging and dementia, cloud computing pipelines, and agentic AI integrations for large-scale neuroscience data.',
        url: 'https://www.linkedin.com/in/stephen-kiilu-401000118/',
        avatar: '/img/team/stephen.png',
        expertise: ['Psychology', 'Aging and Dementia', 'Agentic AI', 'Cloud Compute'],
    },
    {
        name: 'Yang Zhang',
        title: 'Neuroscience PhD Student',
        institution: 'University of Texas at Austin',
        bio: 'Yang is a Neuroscience PhD student developing scalable neuroimaging pipelines, network neuroscience models, and investigating aging and dementia.',
        avatar: '/img/team/yang.png',
        expertise: ['Neuroimaging Pipelines', 'Aging and Dementia', 'Network Neuroscience'],
    },
    {
        name: 'Taylor Grafft',
        title: 'Software Engineer',
        institution: 'Brainlife Core Team',
        bio: 'Taylor focuses on data engineering, cloud infrastructure, DevOps, and Slurm HPC integrations for the brainlife.io ecosystem.',
        url: 'https://www.linkedin.com/in/taylorgrafft',
        avatar: '/img/team/taylor_grafft.jpg',
        expertise: ['Data Engineering', 'Cloud Infrastructure', 'DevOps', 'Slurm HPC'],
    },
    {
        name: 'Nicholas Lee',
        title: 'Software Engineer',
        institution: 'Brainlife Core Team',
        bio: 'Nicholas specializes in front end architecture, user experience design, Next.js, and interactive workflows to make cloud computing intuitive for researchers.',
        url: 'https://www.linkedin.com/in/n-a-lee/',
        avatar: '/img/team/nick_lee.jpg',
        expertise: ['Front End', 'User Experience', 'Next.js & React', 'Interactive Workflows'],
    },
    {
        name: 'Tiffany Hong',
        title: 'Data Engineer',
        institution: 'Brainlife Core Team',
        bio: 'Tiffany is a Data Engineer focused on database architectures, automated data pipelines, and agentic AI workflows.',
        avatar: '/img/team/tippany.png',
        expertise: ['Databases', 'Agentic AI', 'Data Engineering', 'Cloud Storage'],
    },
];

export const COLLABORATORS: TeamMember[] = [
    {
        name: 'Sarah Heilbronner',
        title: 'Assistant Professor',
        institution: 'University of Minnesota',
        bio: 'Together we are working on understanding the connectivity of the Parietal cortex.',
        avatar: '/img/team/Sarah_Heilbronner.png',
        expertise: ['Parietal Cortex', 'Connectivity', 'Neuroanatomy'],
    },
    {
        name: 'Damian Eke',
        title: 'Assistant Professor',
        institution: 'University of Nottingham, UK',
        url: 'https://scholar.google.com/citations?user=exZaJccAAAAJ&hl=en&oi=ao',
        avatar: '/img/team/EkeDamian.jpg',
        expertise: ['Data Ethics', 'Neuroinformatics Governance', 'Responsible AI'],
    },
    {
        name: 'Ricardo Chavarriaga',
        title: 'Professor',
        institution: 'Zurich University of Applied Sciences (ZHAW), Switzerland',
        url: 'https://scholar.google.com/citations?user=ZU1fTMYAAAAJ&hl=en&oi=ao',
        avatar: '/img/team/RIcardoChavarriaga.jpg',
        expertise: ['Artificial Intelligence', 'Brain-Machine Interfaces', 'Neurotechnology'],
    },
    {
        name: 'Fernanda Tovar Moll',
        title: 'MD, Ph.D., CEO',
        institution: "D’Or Institute of Research and Education (IDOR), Brazil",
        avatar: '/img/team/Fernanda_Tovar.png',
        expertise: ['Neuroplasticity', 'Clinical Neuroscience', 'Connectomics'],
    },
    {
        name: 'Amadi Ihunwo',
        title: 'Professor',
        institution: 'University of the Witwatersrand (Wits), South Africa',
        avatar: '/img/team/Amadi_Ihunwo.png',
        expertise: ['Neurobiology', 'Neurogenesis', 'African Neuroscience'],
    },
    {
        name: 'Thomas Nichols',
        title: 'Professor',
        institution: 'Oxford University, UK',
        avatar: '/img/team/Thomas_Nichols.png',
        expertise: ['Neuroimaging Statistics', 'Big Data Neuroscience', 'Methodology'],
    },
    {
        name: 'Alexander Huth',
        title: 'Assistant Professor of Neuroscience and Computer Science',
        institution: 'University of Texas at Austin',
        avatar: '/img/team/Alexander_Huth.png',
        expertise: ['Computational Neuroscience', 'Natural Language', 'Cortical Mapping'],
    },
    {
        name: 'Ariel Rokem',
        title: 'Research Associate Professor, Department of Psychology',
        institution: 'University of Washington',
        url: 'https://scholar.google.com/citations?user=xNYnb6wAAAAJ&hl=en',
        avatar: '/img/team/Ariel_Rokem.png',
        expertise: ['Data Science', 'Computational Neuroimaging', 'Reproducibility'],
    },
    {
        name: 'Elizabeth Lippard',
        title: 'Assistant Professor, Department of Psychiatry and Behavioral Sciences',
        institution: 'Dell Medical Center, University of Texas at Austin',
        avatar: '/img/team/Elizabeth_Lippard.png',
        expertise: ['Psychiatry', 'Behavioral Sciences', 'Clinical Neuroimaging'],
    },
    {
        name: 'Dan Stanzione',
        title: 'Associate Vice President for Research & Executive Director',
        institution: 'Texas Advanced Computing Center (TACC)',
        avatar: '/img/team/Dan_Stanzione.png',
        expertise: ['Supercomputing', 'HPC Architecture', 'Cyberinfrastructure'],
    },
    {
        name: 'Chris Rorden',
        title: 'Professor and Endowed Chair of Neuroscience, Department of Psychology',
        institution: 'University of South Carolina',
        avatar: '/img/team/Chris_Rorden.png',
        expertise: ['NIfTI Tools', 'Clinical Neuroimaging', 'Stroke & Brain Injury'],
    },
    {
        name: 'Russell Poldrack',
        title: 'Professor of Psychology, School of Humanities and Sciences',
        institution: 'Stanford University',
        avatar: '/img/team/Russell_Poldrack.png',
        expertise: ['OpenNeuro', 'Neuroimaging Standards', 'Cognitive Neuroscience'],
    },
    {
        name: 'Daniel J. McDonald',
        title: 'Associate Professor, Department of Statistics',
        institution: 'The University of British Columbia',
        bio: 'Together we are developing approaches to tractography methods optimization.',
        avatar: '/img/team/Daniel_J.png',
        expertise: ['Statistical Machine Learning', 'Tractography Optimization', 'Model Evaluation'],
    },
    {
        name: 'Nicholas Port',
        title: 'Associate Professor of Vision Science and Neuroscience',
        institution: 'Indiana University Bloomington',
        bio: 'Together we are trying to understand brain concussion using brainlife.io.',
        avatar: '/img/team/Nicholas_Port.png',
        expertise: ['Vision Science', 'Concussion Research', 'Oculomotor Tracking'],
    },
    {
        name: 'Anastasia Yendiki',
        title: 'Associate Professor in Radiology',
        institution: 'Harvard Medical School / Massachusetts General Hospital',
        avatar: '/img/team/Anastasia_Yendiki.png',
        expertise: ['TRACULA', 'Diffusion MRI', 'High-Resolution Tractography'],
    },
    {
        name: 'Yaroslav Halchenko',
        title: 'Research Assistant Professor',
        institution: 'Dartmouth College',
        bio: 'Together we are developing technology to connect data across the globe using DataLad.org and brainlife.io.',
        url: 'https://scholar.google.com/citations?user=EbtfZcwAAAAJ&hl=en',
        avatar: '/img/team/yarik.jpg',
        expertise: ['DataLad', 'Debian / NeuroDebian', 'Distributed Data Infrastructure'],
    },
];

export const CONTRIBUTORS: TeamMember[] = [];

export const ALUMNI: TeamMember[] = [
    {
        name: 'Daniel Levitas',
        title: 'Software Developer',
        institution: 'Alumni',
        bio: 'After leaving our team, Dan took on a Data Analyst position in North Carolina.',
        url: 'https://perceptionandneuroimaging.psych.indiana.edu/people/daniellevitas.html',
        avatar: '/img/team/DanLevitas.png',
        expertise: ['Full Stack Development', 'Data Analysis', 'Web Frameworks'],
    },
    {
        name: 'Annie Mackenzie',
        title: 'Lab & Project Manager',
        institution: 'Alumni',
        bio: 'After leaving the lab, Annie took on a position as Global Regulatory Writer.',
        avatar: '/img/team/Annie_Mackenzie.png',
        expertise: ['Project Management', 'Regulatory Writing', 'Lab Operations'],
    },
    {
        name: 'Bradley Caron',
        title: 'Postdoctoral Fellow',
        institution: 'Now: Novartis (Boston, MA)',
        bio: 'After graduating from the lab, Brad took on a position as a Translational Imaging Data Scientist at Novartis (Boston, MA).',
        url: 'https://scholar.google.com/citations?user=fU9K6GgAAAAJ&hl=en',
        avatar: '/img/team/brad.png',
        expertise: ['Translational Imaging', 'Data Science', 'Vision Science'],
    },
    {
        name: 'Ashley Stewart',
        title: 'Visiting Postdoctoral Researcher',
        institution: 'The University of Queensland',
        bio: 'Ashley visited the lab from The University of Queensland.',
        avatar: '/img/team/Ashley_Stewart.png',
        expertise: ['Cognitive Neuroscience', 'Neuroimaging', 'Brain Plasticity'],
    },
    {
        name: 'Daniela Reyes',
        title: 'Undergraduate Research Assistant',
        institution: '2024 Behavioral Data Science Intern',
        bio: 'Daniela was an Undergraduate Research Assistant and 2024 Behavioral Data Science Intern.',
        avatar: '/img/team/Daniela_Reyes.png',
        expertise: ['Behavioral Data Science', 'Data Analysis'],
    },
    {
        name: 'Dheeraj Bhatia',
        title: 'Software Engineer',
        institution: 'Alumni',
        bio: 'Dheeraj was an integral software engineer on brainlife.io, contributing to cloud computing and UI infrastructure.',
        url: 'https://www.linkedin.com/in/devdheerajbhatia/',
        avatar: '/img/team/dheerajbhatia.jpeg',
        expertise: ['Software Engineering', 'Cloud Platforms', 'Web Apps'],
    },
    {
        name: 'Mohammed Mehboob',
        title: 'Research Assistant',
        institution: 'Now: Adobe',
        bio: 'After leaving the lab, Mohammed took a position as an Associate Consultant within Consulting at Adobe.',
        avatar: '/img/team/Mohammed_Mehboob.png',
        expertise: ['Consulting', 'Data Analytics', 'Software Solutions'],
    },
    {
        name: 'Cat Leal',
        title: 'Undergraduate Research Assistant',
        institution: '2023 Behavioral Data Science Intern',
        bio: 'After graduating from the lab, Cat started a Masters in Data Science at The University of Texas at Austin.',
        avatar: '/img/team/Cat_Leal.png',
        expertise: ['Data Science', 'Behavioral Research', 'Machine Learning'],
    },
    {
        name: 'Julia Guiomar (Guio) Niso Galán',
        title: 'CRCNS Research Scientist',
        institution: 'Now: Cajal Institute (Madrid)',
        bio: 'After leaving the lab, Guio started her research group at Cajal Institute in Madrid.',
        url: 'https://scholar.google.com/citations?user=xqxSCSkAAAAJ',
        avatar: '/img/team/guio_meglab.png',
        expertise: ['MEG / EEG', 'BIDS Standards', 'Open Science'],
    },
    {
        name: 'Soichi Hayashi',
        title: 'Software Engineer',
        institution: 'Now: Fintech',
        bio: 'After leaving the lab, Soichi took on a position as a Software Developer in a Fintech Company.',
        url: 'https://soichi.us',
        avatar: '/img/team/soichi.jpg',
        expertise: ['Cloud Architecture', 'HPC Orchestration', 'Distributed Systems'],
    },
    {
        name: 'Om Pandey',
        title: 'Masters Student',
        institution: 'Now: DTCC',
        bio: 'After graduating with his Masters in Computer Science from UT, Om began working as a Machine Learning Engineer at the Depository Trust & Clearing Corporation (DTCC).',
        avatar: '/img/team/Om_Pandey.png',
        expertise: ['Machine Learning', 'Computer Science', 'Cloud Infrastructure'],
    },
    {
        name: 'Kunjal Shah',
        title: 'Masters Research Assistant',
        institution: 'Now: NVIDIA',
        bio: 'After graduating from the lab, Kunjal started a job as an engineer at NVIDIA.',
        avatar: '/img/team/Kunjal_Shah.png',
        expertise: ['GPU Acceleration', 'Computer Engineering', 'Systems Optimization'],
    },
    {
        name: 'Sophia Vinci-Booher',
        title: 'NSF SBE Postdoctoral Researcher',
        institution: 'Now: Assistant Professor, Vanderbilt University',
        bio: 'After graduating from the lab, Sophia started her lab at Vanderbilt University.',
        url: 'https://scholar.google.com/citations?user=xNYnb6wAAAAJ&hl=en',
        avatar: '/img/team/sophia_cropped_750x750.jpg',
        expertise: ['Developmental Neuroscience', 'White Matter', 'Learning Systems'],
    },
    {
        name: 'Antonio Fernandez',
        title: 'NIH Postdoctoral Fellow',
        institution: 'Now: UI/UX Industry',
        bio: 'After leaving the lab, Dr. Fernandez started working as UI/UX Researcher in the industry.',
        avatar: '/img/team/Antonio_Fernandez.png',
        expertise: ['UI/UX Research', 'Cognitive Science', 'Human Factors'],
    },
    {
        name: 'Sandra Hanekamp',
        title: 'Postdoctoral Fellow',
        institution: 'Now: NordicNeuroLab',
        bio: 'After graduating from the lab, Sandra took a position at NordicNeuroLab.',
        url: 'https://scholar.google.com/citations?user=HpFvfUsAAAAJ&hl=en&oi=ao',
        avatar: '/img/team/sandra.jpg',
        expertise: ['Visual Neuroscience', 'Clinical Translation', 'Scientific Outreach'],
    },
    {
        name: 'Brent C. McPherson',
        title: 'Ph.D. Student',
        institution: 'Now: McGill University',
        bio: 'After graduating from the lab, Brent took a Postdoctoral Researcher position at McGill University.',
        url: 'https://scholar.google.com/citations?user=UTKS08kAAAAJ&hl=en&oi=sra',
        avatar: '/img/team/brent.jpg',
        expertise: ['Diffusion MRI', 'Structural Networks', 'Tractography Apps'],
    },
    {
        name: 'Daniel N. Bullock',
        title: 'Ph.D. Student',
        institution: 'Now: University of Minnesota',
        bio: 'After graduating from the lab, Dan took on a position as Postdoctoral Researcher at the University of Minnesota.',
        url: 'https://scholar.google.com/citations?user=PhaFy78AAAAJ&hl=en',
        avatar: '/img/team/dan.jpg',
        expertise: ['White Matter Anatomy', 'Automated Segmentation', 'Open Science'],
    },
    {
        name: 'Giulia Berto',
        title: 'Postdoctoral Fellow',
        institution: 'Now: Data Scientist',
        bio: 'After leaving the lab, Giulia took a position as a Data Scientist.',
        url: 'https://scholar.google.com/citations?user=T2CydDUAAAAJ&hl=en',
        avatar: '/img/team/giulia3.png',
        expertise: ['Concussion Research', 'Machine Learning', 'Data Science'],
    },
    {
        name: 'Ilaria Sani',
        title: 'Visiting Postdoc',
        institution: 'Now: Assistant Professor, University of Geneva',
        bio: 'Ilaria was visiting from the Laboratory of Winrich Freiwald at Rockefeller University. After visiting the lab, Ilaria took an Assistant Professor position at the University of Geneva.',
        avatar: '/img/team/Ilaria_Sani.png',
        expertise: ['Primate & Human Neuroscience', 'Visual Cognition', 'Cortical Networks'],
    },
    {
        name: 'Josiah Leong',
        title: 'Postdoctoral Fellow',
        institution: 'Now: Assistant Professor, University of Arkansas',
        bio: 'After working in the lab, Josiah started his lab and became Assistant Professor in Psychology at the University of Arkansas.',
        url: 'https://scholar.google.com/citations?user=Josiah+Leong',
        avatar: '/img/team/josiah.jpg',
        expertise: ['Decision Neuroscience', 'ABCD Study', 'White Matter Anatomy'],
    },
    {
        name: 'Ricardo Fabrega',
        title: 'Undergraduate Research Assistant',
        institution: 'Now: Uniformed Services University (Bethesda, MD)',
        bio: 'After leaving the lab, Ricardo won a prestigious Medical Student Scholarship at the F. Edward Hébert School of Medicine of the Uniformed Services University of the Health Sciences in Bethesda, Maryland.',
        url: 'https://www.linkedin.com/in/stuckricardo/',
        avatar: '/img/team/ricardo.jpg',
        expertise: ['Pre-Med', 'Clinical MRI', 'Neuroimaging Workflows'],
    },
    {
        name: 'Yiming Qian',
        title: 'Undergraduate Research Assistant',
        institution: 'Now: Penn State University',
        bio: 'After leaving the lab, Yiming started Graduate School at Penn State University.',
        avatar: '/img/team/yiming.png',
        expertise: ['Data Science', 'Neuroimaging Analysis', 'Python Workflows'],
    },
    {
        name: 'Lindsey Kitchell',
        title: 'Ph.D. Student',
        institution: 'Now: Johns Hopkins Applied Physics Lab',
        bio: "After leaving the lab, Lindsey took on a position as Senior Professional Scientist at Johns Hopkins University's Applied Physics Laboratory.",
        url: 'https://lindseykitchell.weebly.com/',
        avatar: '/img/team/lindseykitchell.jpg',
        expertise: ['Neuro-AI', 'Connectomics', 'Early Platform Apps'],
    },
    {
        name: 'Shiloh Echevarria-Cooper',
        title: 'Undergraduate Research Assistant',
        institution: 'Now: Northwestern University',
        bio: 'After leaving the lab, Shiloh started graduate school at Northwestern University.',
        url: 'https://scholar.google.com/citations?user=YUhVZFsAAAAJ&hl=en',
        avatar: '/img/team/shiloh.jpg',
        expertise: ['Neural Circuits', 'Electrophysiology', 'Cognitive Neuroscience'],
    },
    {
        name: 'Aman Arya',
        title: 'Undergraduate Research Assistant',
        institution: 'Now: Amazon',
        bio: 'After leaving the lab, Aman took a job at Amazon.',
        url: 'https://www.linkedin.com/in/aman-arya22/',
        avatar: '/img/team/aman.jpg',
        expertise: ['AWS Cloud', 'Jetstream Computing', 'Software Engineering'],
    },
    {
        name: 'Cesar F. Caiafa',
        title: 'Visiting Scientist',
        institution: 'Now: IAR / University of Buenos Aires',
        bio: 'After working in the lab, Cesar returned to Argentina to work at the Argentinean Radioastronomy Institute (IAR) and as an Adjunct Professor at the Faculty of Engineering, University of Buenos Aires.',
        url: 'https://ccaiafa.wixsite.com/cesar',
        avatar: '/img/team/cesar.jpg',
        expertise: ['Tensor Decomposition', 'Signal Processing', 'Neuroimaging Algorithms'],
    },
    {
        name: 'Steven O’Riley',
        title: 'High-school and Undergraduate Research Assistant',
        institution: 'Alumni',
        bio: 'After leaving the lab, Steven took a data science job.',
        url: 'https://www.linkedin.com/in/sporiley/',
        avatar: '/img/team/steven340.jpg',
        expertise: ['Data Science', 'Software Development', 'HPC Workflows'],
    },
    {
        name: 'Melanie Collier',
        title: 'Lab Manager',
        institution: 'Now: UCLA',
        bio: 'After leaving the lab, Melanie started a Ph.D. in Cognitive Neuroscience at the University of California, Los Angeles.',
        url: 'https://scholar.google.com/citations?user=IomAkw8AAAAJ&hl=en',
        avatar: '/img/team/mel_collier.jpeg',
        expertise: ['Cognitive Neuroscience', 'Lab Operations', 'Behavioral Studies'],
    },
    {
        name: 'Sydney Fulton',
        title: 'Undergraduate Research Assistant',
        institution: 'Now: Texas A&M University',
        bio: 'After leaving the lab, Sydney took a research assistant position at Texas A&M University.',
        avatar: '/img/team/Sydney_Fulton.png',
        expertise: ['Neuroimaging Pipelines', 'Research Analysis', 'Data QA'],
    },
    {
        name: 'Anna Bostoganashvili',
        title: '2025 Women in Neuroscience Fellow',
        institution: 'Mt Sinai / Centre College',
        bio: 'After leaving the lab, Anna took a research assistant position in New York.',
        avatar: '/img/team/Anna_Bostoganashvili.png',
        expertise: ['Women in Neuroscience', 'Clinical Research', 'Neuroscience'],
    },
    {
        name: 'Karen Herrera',
        title: '2025 Women in Neuroscience Intern',
        institution: 'Vanderbilt University',
        bio: 'After leaving the lab, Karen took a research position.',
        avatar: '/img/team/Karen_Herrera.png',
        expertise: ['Women in Neuroscience', 'Neuroscience', 'Data Processing'],
    },
    {
        name: 'Sihang (Suna) Guo',
        title: 'Ph.D. Student',
        institution: 'Now: UC Berkeley',
        bio: 'After leaving the lab, Suna continued her PhD at The University of California, Berkeley.',
        avatar: '/img/team/Sihang_(Suna).png',
        expertise: ['Machine Learning', 'Cognitive Neuroscience', 'fMRI Analysis'],
    },
    {
        name: 'Sangmin (Alden) Yi',
        title: 'Post-Bachelor Research Assistant',
        institution: 'Now: Indiana University Bloomington',
        bio: 'After leaving the lab, Alden began his PhD at Indiana University Bloomington.',
        avatar: '/img/team/Sangmin_(Alden).png',
        expertise: ['Computational Neuroscience', 'fMRI Data Analysis', 'Pipeline Development'],
    },
    {
        name: 'Sohmee Kim',
        title: 'Undergraduate Research Assistant',
        institution: 'Now: UT Austin (Pharm.D)',
        bio: 'After leaving the lab, Sohmee started her Pharm.D at the University of Texas at Austin.',
        avatar: '/img/team/Sohmee_Kim.png',
        expertise: ['Pharmacotherapy', 'Behavioral Neuroscience', 'Data Collection'],
    },
    {
        name: 'Alisha Flexwala',
        title: 'Undergraduate Research Assistant',
        institution: 'Alumni',
        bio: 'Alisha was an Undergraduate Research Assistant contributing to data curation and open science pipelines.',
        avatar: '/img/team/Alisha_Flexwala.png',
        expertise: ['Neuroscience Research', 'Data Curation', 'Open Science'],
    },
];
